name: orangepi-5b
soc: rk3588
console: "ttyS2,1500000n8"
partitions:
  boot_mb: 256
  root_mb: 4096
bootargs_extra:
  - "cma=256M"
  - "panic=5"
files:
  kernel_image: Image
  dtb: rk3588-orangepi-5-plus.dtb
  initrd: initrd.img
  uboot_spl: idbloader.img
  uboot_itb: u-boot.itb
